var aNanitemData = [
		[
			{
				url:'https://www.kuazhu.com',
				img:'images/p1.png',
				name:'小米MX1',
				price:'3299元起',
				tag:'新品'
			},
			{
				url:'https://www.kuazhu.com',
				img:'images/p1.png',
				name:'小米MX1',
				price:'3299元起',
				tag:'新品'
			},
		],
		[
			{
				url:'https://www.kuazhu.com',
				img:'images/p2.png',
				name:'小米MX2',
				price:'3299元起',
				tag:'新品'
			},
			{
				url:'https://www.kuazhu.com',
				img:'images/p2.png',
				name:'小米MX2',
				price:'3299元起',
				tag:'新品'
			},
		],
		[
			{
				url:'https://www.kuazhu.com',
				img:'images/p3.png',
				name:'小米MX3',
				price:'3299元起',
				tag:'新品'
			},
			{
				url:'https://www.kuazhu.com',
				img:'images/p3.png',
				name:'小米MX3',
				price:'3299元起',
				tag:'新品'
			},
		],
		[],
		[],
		[],
		[],
		[],
	];
var aCateitemData = [
	[
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX1'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX1'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX1'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX1'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX1'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX1'
		},
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX2'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX2'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX2'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX2'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX2'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MIX2'
		},
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/p3.jpg',
			name:'小米MIX3'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p3.jpg',
			name:'小米MIX3'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p3.jpg',
			name:'小米MIX3'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p3.jpg',
			name:'小米MIX3'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p3.jpg',
			name:'小米MIX3'
		},
		{
			url:'http://www.baidu.com',
			img:'images/p3.jpg',
			name:'小米MIX3'
		},
	],
	[],
	[],
	[],
	[],
	[],
	[],
	[],
]
var aElecData = [
	[
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			top:{
				url:'http://www.baidu.com',
				img:'images/ca.png',
				name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
				price:'3699'
			},
			bottom:{
				url:'http://www.baidu.com',
				txt:'浏览更多',
				tag:'热门',
				iconfont:'&#xe615;'
			}
		}
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'这是第二页',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			top:{
				url:'http://www.baidu.com',
				img:'images/ca.png',
				name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
				price:'3699'
			},
			bottom:{
				url:'http://www.baidu.com',
				txt:'浏览更多',
				tag:'热门',
				iconfont:'&#xe615;'
			}
		}
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'这是第三页',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			top:{
				url:'http://www.baidu.com',
				img:'images/ca.png',
				name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
				price:'3699'
			},
			bottom:{
				url:'http://www.baidu.com',
				txt:'浏览更多',
				tag:'热门',
				iconfont:'&#xe615;'
			}
		}
	],
	[
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'这是第四页',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			url:'http://www.baidu.com',
			img:'images/p1.jpg',
			name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
			desc:'Unibody 全陶瓷',
			price_now:'3699',
			price_del:'4699元',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我不是来评价的电视的我是来拉仇恨的,哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈',
				author:'kauzhu'
			}
		},
		{
			top:{
				url:'http://www.baidu.com',
				img:'images/ca.png',
				name:'小米MX2 8GB+128GB 黑bbbbbbbbbb',
				price:'3699'
			},
			bottom:{
				url:'http://www.baidu.com',
				txt:'浏览更多',
				tag:'热门',
				iconfont:'&#xe615;'
			}
		}
	]
]